### ISSUE TITLE
Serveur de test inaccessible

### ISSUE THREAD

**Issue by Cochonours** [ocsigen/ocsigen.org#10]
Bonjour,

Tous les tests du manuel sur le site ocsigen pointent vers le serveur http://tests.ocsigen.org qui ne répond même pas aux pings...

**Comment by vasilisp** [comment]
I sort of fixed this, not by reinstating `tests.ocsigen.org`, but by removing the links to it. (We are trying to simplify our infrastructure, so `tests.ocsigen.org` may never come back.) Feel free to reopen this if I have missed any references, messed up the syntax, etc.

**Comment by Drup** [comment]
I'm not sure why, but this is fixed.
