### ISSUE TITLE
Faute de frappe dans le tuto sur les liens

### ISSUE THREAD

**Issue by Cochonours** [ocsigen/ocsigen.org#11]
Sur ce tuto : https://ocsigen.org/eliom/manual/server-links , il est écrit "Eliom_content.​Html5.​D.​a takes as first parameter the service you want to link to. The third parameter is the text of the link. The last parameter is for GET parameters you want to put in the link."
Le libellé du lien devrait être le second paramètre, et non pas le troisième !

**Comment by balat** [comment]
Thanks! Fixed by https://github.com/ocsigen/eliom/commit/cb4b1772a538843d05966685a87031ea62c24bdc
