### ISSUE TITLE
Exemple déroutant dans le tuto sur les widgets

### ISSUE THREAD

**Issue by Cochonours** [ocsigen/ocsigen.org#12]
Dans la page du tuto client server ( https://ocsigen.org/tuto/manual/tutowidgets ), le fait que les boîtes avec écrit "click me" soient une capture d'écran ( https://ocsigen.org/tuto/files/tutorial/tutowidgets/ex-final.png ) n'est pas clair du tout. Il faudrait soit mettre avant un titre explicitant qu'il s'agit d'un exemple du résultat final, soit directement mettre l'exemple que le tuto va s'évertuer à expliquer !

**Comment by balat** [comment]
Il est écrit "screenshot" en gros sur les images ;) mais effectivement ce n'est peut-être pas suffisant ?
Peut-être mettre l'entourage des fenêtres ?
Mettre un exemple qui fonctionne est un peu compliqué en terme de maintenance j'ai plutôt tendance à vouloir simplifier l'infrastructure.
Contributions bienvenues ;)

**Comment by Cochonours** [comment]
Ah, je viens de trouver un autre bug alors ^^

Je viens de retourner sur la page parce que je n'avais pas vu écrit "screenshot" du tout sur les images et je craignais pour ma vue, et du coup j'ai trouvé le message en question mais il n'apparaît pas sur les images chez moi ! En effet il apparaît à droite des images, en dehors du flux de la page donc je n'y avais pas prêté attention du tout... Comme son affichage est géré par une règle css "p.screenshot::after" il faudrait revoir cette règle afin que l'overlay soit bien sur l'image et non à côté.

Je précise, j'utilise firefox sous ubuntu... et je ne pense pas que mes extensions soient la cause du problème de positionnement de l'overlay.


PS : par rapport aux exemples et au fait que le serveur de test soit enterré, pourquoi ne pas faire tourner les exemples sur le même serveur ? Ça simplifierait la maintenance tout en garantissant que les liens ne seront jamais HS (ce qui est un des grands intérêts d'ocsigen pour moi...). De plus, les exemples ne mentent jamais, contrairement aux tutos qui peuvent ne pas être à jour :p

**Comment by balat** [comment]
En effet ! Merci. J'ai corrigé.
Pour le tests, en effet on essaiera de la remettre.
Pour l'instant nous sommes un peu occupés avec la release d'Eliom 5 ;)
