### ISSUE TITLE
Broken link between parts of ocsigen.org site

### ISSUE THREAD

**Issue by Cochonours** [ocsigen/ocsigen.org#13]
If you go to this page : https://ocsigen.org/howto/img and click on "external service" (at the end, just before "download full code") the page will say "not found". I guess the "manual" and "howto" are not handled by the same ocsigen server, but why so? It would be good for the ocsigen website to have no internal broken links in order to demonstrate the usefulness of eliom services! This is but one example of broken links within ocsigen.org website... :(

**Comment by vasilisp** [comment]
Thank you! I fixed it. The URL for the services documentation had changed. The manual and the howto's are on the same server (but produced differently).
