### ISSUE TITLE
Dead link in howto compile

### ISSUE THREAD

**Issue by Cochonours** [ocsigen/ocsigen.org#14]
In page https://ocsigen.org/howto/compile there is a link toward https://ocsigen.org/eliom/manual/client-compiling#h5o-2 and this ends up with a page not found error...

**Comment by vasilisp** [comment]
This page [exists for Eliom 2.x](https://ocsigen.org/eliom/2.2.2/manual/client-compiling), but not for modern versions. It was incomplete anyway. (In fact, even https://ocsigen.org/howto/compile doesn't look all that great.) I guess our current recommendation is to start with [`eliom-distillery`](http://ocsigen.org/eliom/manual/workflow-distillery), so we should revamp the documentation to make its documentation more prominent.

**Comment by Cochonours** [comment]
It's true that the whole page is unoptimal haha :) I came there because I wanted to know a way to compile my project without launching the server afterwards (make xxx compiles and launches), and have yet to find a solution...

**Comment by vasilisp** [comment]
I updated the page. Are you using `eliom-distillery`? You can build the project without launching the server by typing `make` in place of `make test.opt` / `make test.byte`.

**Comment by Cochonours** [comment]
Oh yes, that was it ^^
