### ISSUE TITLE
error on the doc of lwt

### ISSUE THREAD

**Issue by c-cube** [ocsigen/ocsigen.org#20]
https://ocsigen.org/lwt/dev/api/Ppx_lwt :

> Error
Ocaml_lexer.Error(_, _)
Ocisgen running in debug mode

on the left panel.

**Comment by aantron** [comment]
This was fixed in https://github.com/ocsigen/lwt/issues/263 and can be closed.

**Comment by vasilisp** [comment]
@aantron thanks for the fix!
