### ISSUE TITLE
Site appears to be down

### ISSUE THREAD

**Issue by aantron** [ocsigen/ocsigen.org#31]
Seeing

```
Internal Server Error

Error 500

Unix.Unix_error(Unix.EPIPE, "write", "")
(Ocsigen running in debug mode)
```

Originally reported by @keyansol in ocsigen/lwt#331.

**Comment by dannywillems** [comment]
up now

**Comment by coolmenu** [comment]
is ocisgen.org down again? I cannot connect in china by ss proxy.

**Comment by vasilisp** [comment]
Yes, it is down due to an outage in the INRIA network. We are aware of it and in touch with the INRIA admins.
