### ISSUE TITLE
ocsigen.org is down

### ISSUE THREAD

**Issue by bobbypriambodo** [ocsigen/ocsigen.org#34]
Hi, just want to notify that currently the ocsigen.org site cannot be accessed, returning `ERR_CONNECTION_REFUSED` on Chrome. Sorry if you're already aware of it! :)

**Comment by gasche** [comment]
Note: there is a [discuss thread](https://discuss.ocaml.org/t/ocsigen-org-is-down/876) where people wonder about the recent outages, and maybe someone that knows their cause could be interested in giving a summary there.

**Comment by balat** [comment]
Inria is currently working on a reorganization of their network.
Unfortunately it does not happen as expected.

If I understand well the problem, a network file system that was used by the server has been moved to a different subnetwork, which makes it inaccessible from the server ...
I hope a solution will be found as soon as possible ...

**Comment by balat** [comment]
Inria engineers completed the migration of all the server to the new subnetwork yesterday afternoon.
We updated the DNS.
Everything should now be in order.

Unfortunately, another intervention is scheduled in a few days. We'll try to make the down time as short as possible this time ...

**Comment by bobbypriambodo** [comment]
Thanks for the update, @balat! I can confirm that the site is now working. Should I leave this issue open at least until the next intervention? (If not you can go ahead and close it :slightly_smiling_face:)
