### ISSUE TITLE
/install out of date

### ISSUE THREAD

**Issue by mlinksva** [ocsigen/ocsigen.org#9]
http://ocsigen.org/install

* Link to mailing list doesn't work, is https://sympa.inria.fr/sympa/arc/ocsigen elsewhere on the site
* Ubuntu support seems to be identical to Debian now https://launchpad.net/ubuntu/+source/eliom
* Should https://registry.hub.docker.com/u/ocsigen/ocsigen/ be listed as an easy install option?

Common to all /install and other sub-pages:

* The 'Je Suis Charlie' banner overflows into the main content area -- compare with oscigen.org home page (tried Firefox and Chromium)

**Comment by mlinksva** [comment]
Additionally, in order to install using opam on Debian, I also needed the camlp4-extra and opam packages, which are not listed in http://ocsigen.org/install#source

**Comment by balat** [comment]
Thank you. I think everything is fixed.
I don't know if the docker package is actively maintained (and in any case, not officialy).
Reopen if you still see problems.
Vincent
